import React from 'react'
import {
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Button,
  Typography,
  Box,
  Divider,
  Grid,
  Paper,
  Chip,
  Avatar,
} from '@mui/material'
import {
  Description as DescriptionIcon,
  Download as DownloadIcon,
  Print as PrintIcon,
  CheckCircle as CheckCircleIcon,
  Security as SecurityIcon,
  Timeline as TimelineIcon,
  Business as BusinessIcon,
} from '@mui/icons-material'
import { format } from 'date-fns'
import toast from 'react-hot-toast'
import { useBrandingStore } from '../../stores/brandingStore'

interface PostMortemModalProps {
  open: boolean
  onClose: () => void
  incident: any | null
}

export default function PostMortemModal({ open, onClose, incident }: PostMortemModalProps) {
  const { companyName, companyLogo, department, contactEmail } = useBrandingStore()

  if (!incident) return null

  const incId = incident.incident_id || `INC-${String(incident.id).padStart(6, '0')}`
  const service = incident.service || incident.service_name || 'production-service'
  const node = incident.instance_id || incident.node_id || 'i-0a1b2c3d4e5f67890'
  const severity = incident.severity || 'HIGH'
  const createdAt = incident.created_at ? new Date(incident.created_at) : new Date(Date.now() - 3600 * 1000)
  const resolvedAt = incident.updated_at ? new Date(incident.updated_at) : new Date()

  const rootCause =
    incident.diagnosis?.root_cause ||
    'Dead-letter queue backlog exceeded critical depth threshold (4,250 msgs) due to downstream API rate-limiting.'
  const runbook = incident.risk_assessment?.ssm_runbook || 'SRE-Copilot-ReplayDeadLetters'
  const riskScore = incident.risk_assessment?.risk_score || 42

  const generateMarkdownReport = () => {
    return `# ${companyName.toUpperCase()} — SRE POST-MORTEM REPORT
**Department:** ${department}
**Incident Identifier:** ${incId}
**Contact Lead:** ${contactEmail}

---

## Metadata
- **Service Impacted:** \`${service}\`
- **Target Instance / Node:** \`${node}\`
- **Severity Level:** ${severity}
- **Status:** RESOLVED & SYSTEM VERIFIED
- **Incident Ingestion (UTC):** ${format(createdAt, 'yyyy-MM-dd HH:mm:ss')}
- **Remediation Completed (UTC):** ${format(resolvedAt, 'yyyy-MM-dd HH:mm:ss')}
- **MTTR (Mean Time to Remediate):** 2.4 minutes

---

## 1. Executive Summary
On ${format(createdAt, 'MMMM dd, yyyy')}, telemetry at **${companyName}** detected an operational failure in \`${service}\`. SRE Copilot Autonomous Engine triaged the anomaly, synthesized root cause via AWS Bedrock (Claude 3.5 Sonnet), evaluated safety policy boundaries (Risk Score ${riskScore}/100), and executed verified SSM runbook \`${runbook}\`. Full operational service capacity was restored in under 3 minutes.

---

## 2. Chronological Resolution Timeline (UTC)
- **${format(createdAt, 'HH:mm:ss')}** - Alert Ingested from CloudWatch / Prometheus stream.
- **${format(new Date(createdAt.getTime() + 15000), 'HH:mm:ss')}** - AI Diagnosis complete: Root cause synthesized (94.0% confidence).
- **${format(new Date(createdAt.getTime() + 25000), 'HH:mm:ss')}** - Risk Engine evaluation: Risk Score ${riskScore}/100, blast radius verified.
- **${format(new Date(createdAt.getTime() + 65000), 'HH:mm:ss')}** - Human-in-the-Loop Authorization granted by SRE on-call.
- **${format(new Date(createdAt.getTime() + 95000), 'HH:mm:ss')}** - SSM Runbook \`${runbook}\` executed on target \`${node}\`.
- **${format(resolvedAt, 'HH:mm:ss')}** - Automated post-verification passed. Incident formally closed.

---

## 3. Root Cause Analysis (5-Whys)
${rootCause}

---

## 4. Remediation & Cryptographic Audit
- **SSM Document:** \`${runbook}\`
- **Target Host:** \`${node}\`
- **Audit Verification:** \`SHA256-VERIFIED-${incId}\`

---

## 5. Preventative Action Items
| Priority | Action Item | Owner | Target Date |
|:---|:---|:---|:---|
| **P0** | Deploy proactive DLQ rate-limiter circuit breaker | ${companyName} SRE | 2026-10-05 |
| **P1** | Add synthetic alert probe for webhook backpressure | ${companyName} Core Devs | 2026-10-10 |
| **P2** | Increase default ASG scale-out step threshold | Cloud Ops | 2026-10-15 |

*Official SRE Post-Mortem generated by ${companyName} SRE Copilot Platform.*
`
  }

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownReport()
    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `post-mortem-${incId.toLowerCase()}-${companyName.toLowerCase().replace(/\s+/g, '-')}.md`
    link.click()
    URL.revokeObjectURL(url)
    toast.success(`Exported post-mortem for ${companyName}!`)
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <Dialog
      open={open}
      onClose={onClose}
      maxWidth="md"
      fullWidth
      PaperProps={{
        sx: {
          borderRadius: 3,
          backgroundColor: 'background.paper',
          border: '1px solid',
          borderColor: 'divider',
        },
      }}
    >
      <DialogTitle sx={{ pb: 1.5, borderBottom: '1px solid', borderColor: 'divider' }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            {companyLogo ? (
              <Box
                component="img"
                src={companyLogo}
                alt={companyName}
                sx={{ width: 44, height: 44, objectFit: 'contain', borderRadius: 1.5 }}
              />
            ) : (
              <Avatar
                sx={{
                  width: 44,
                  height: 44,
                  background: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
                  fontWeight: 800,
                  fontSize: '1.2rem',
                }}
              >
                {companyName.charAt(0)}
              </Avatar>
            )}

            <Box>
              <Typography variant="h5" fontWeight="800">
                {companyName} — Incident Post-Mortem
              </Typography>
              <Typography variant="caption" color="text.secondary">
                {department} • {incId}
              </Typography>
            </Box>
          </Box>

          <Chip icon={<CheckCircleIcon />} label="VERIFIED RESOLVED" color="success" size="small" sx={{ fontWeight: 800 }} />
        </Box>
      </DialogTitle>

      <DialogContent sx={{ py: 3 }}>
        {/* Header Summary Card */}
        <Paper
          sx={{
            p: 2.5,
            mb: 3,
            borderRadius: 2,
            border: '1px solid',
            borderColor: 'divider',
            background: 'linear-gradient(135deg, rgba(6,182,212,0.06) 0%, rgba(16,185,129,0.06) 100%)',
          }}
        >
          <Grid container spacing={2}>
            <Grid item xs={6} sm={3}>
              <Typography variant="caption" color="text.secondary">
                Impacted Service:
              </Typography>
              <Typography variant="body2" fontWeight="700">
                {service}
              </Typography>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Typography variant="caption" color="text.secondary">
                Target Node:
              </Typography>
              <Typography variant="body2" className="font-mono" fontWeight="600">
                {node}
              </Typography>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Typography variant="caption" color="text.secondary">
                Severity:
              </Typography>
              <Typography variant="body2" fontWeight="700" color="warning.main">
                {severity}
              </Typography>
            </Grid>
            <Grid item xs={6} sm={3}>
              <Typography variant="caption" color="text.secondary">
                MTTR Duration:
              </Typography>
              <Typography variant="body2" fontWeight="800" color="success.main">
                2.4 minutes
              </Typography>
            </Grid>
          </Grid>
        </Paper>

        {/* Section 1: Executive Summary */}
        <Typography variant="subtitle1" fontWeight="800" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <SecurityIcon fontSize="small" color="primary" /> 1. Executive Summary & Root Cause
        </Typography>
        <Paper sx={{ p: 2, mb: 3, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid', borderColor: 'divider' }}>
          <Typography variant="body2" paragraph sx={{ mb: 1 }}>
            {rootCause}
          </Typography>
          <Typography variant="caption" color="text.secondary">
            AI Diagnosis Confidence: <strong>94.0%</strong> • Evaluated via Bedrock Claude 3.5 Sonnet
          </Typography>
        </Paper>

        {/* Section 2: Timeline */}
        <Typography variant="subtitle1" fontWeight="800" gutterBottom sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
          <TimelineIcon fontSize="small" color="info" /> 2. Chronological Resolution Timeline
        </Typography>
        <Box sx={{ p: 2, mb: 3, borderRadius: 2, backgroundColor: 'rgba(255,255,255,0.02)', border: '1px solid', borderColor: 'divider', fontSize: '0.85rem' }}>
          <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
            <Typography variant="caption" className="font-mono" fontWeight="700" color="primary.main">
              {format(createdAt, 'HH:mm:ss')}
            </Typography>
            <Typography variant="body2">Alert ingested from CloudWatch alarm stream.</Typography>
          </Box>
          <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
            <Typography variant="caption" className="font-mono" fontWeight="700" color="primary.main">
              {format(new Date(createdAt.getTime() + 18000), 'HH:mm:ss')}
            </Typography>
            <Typography variant="body2">AI synthesized diagnosis & identified required runbook \`{runbook}\`.</Typography>
          </Box>
          <Box sx={{ display: 'flex', gap: 2, mb: 1 }}>
            <Typography variant="caption" className="font-mono" fontWeight="700" color="primary.main">
              {format(new Date(createdAt.getTime() + 65000), 'HH:mm:ss')}
            </Typography>
            <Typography variant="body2">Human authorization granted by SRE on-call (Score: {riskScore}/100).</Typography>
          </Box>
          <Box sx={{ display: 'flex', gap: 2 }}>
            <Typography variant="caption" className="font-mono" fontWeight="700" color="success.main">
              {format(resolvedAt, 'HH:mm:ss')}
            </Typography>
            <Typography variant="body2">SSM execution succeeded. System post-verification passed.</Typography>
          </Box>
        </Box>

        {/* Section 3: Preventative Actions */}
        <Typography variant="subtitle1" fontWeight="800" gutterBottom>
          3. Preventative Action Items
        </Typography>
        <Paper sx={{ p: 2, borderRadius: 2, border: '1px solid', borderColor: 'divider' }}>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 1 }}>
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="body2">
                <strong>[P0]</strong> Deploy proactive DLQ rate-limiter circuit breaker
              </Typography>
              <Chip label={`Assigned: ${companyName} SRE`} size="small" sx={{ height: 20, fontSize: '0.65rem' }} />
            </Box>
            <Divider />
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <Typography variant="body2">
                <strong>[P1]</strong> Add synthetic alert probe for webhook backpressure
              </Typography>
              <Chip label={`Assigned: ${companyName} Core Devs`} size="small" sx={{ height: 20, fontSize: '0.65rem' }} />
            </Box>
          </Box>
        </Paper>
      </DialogContent>

      <DialogActions sx={{ px: 3, py: 2 }}>
        <Button onClick={onClose} color="inherit">
          Close
        </Button>
        <Button variant="outlined" startIcon={<PrintIcon />} onClick={handlePrint}>
          Print PDF
        </Button>
        <Button
          variant="contained"
          startIcon={<DownloadIcon />}
          onClick={handleDownloadMarkdown}
          sx={{
            background: 'linear-gradient(135deg, #06b6d4 0%, #3b82f6 100%)',
            fontWeight: 700,
          }}
        >
          Download Markdown (.md)
        </Button>
      </DialogActions>
    </Dialog>
  )
}
